/**
 * Created by Caitlin on 1/27/2016.
 */
enum P {START, END, TEMP, MENU_HOME, M_STATUS, M_AGENDA, M_TODO, M_TUTORIAL, BEDROOM, KITCHEN, LIVINGROOM,
    STREET, BUS_ENTRANCE, BUS_SEAT, OFFICE_DESK, OFFICE_BREAKROOM, OFFICE_HALLWAY, OFFICE_MEETING,
    LUNCH, DINNER, CAR
}
